apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "dapperdino-0160"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "dapperdino-0160"
    spec:
      containers:
        - name: "dapperdino-0160"
          image: "dapperdino.azurecr.io/dapperdino"
          ports:
          - containerPort: 80