apiVersion: v1
kind: Service
metadata:
    name: "dapperdino-0160"
    labels:
        app: "dapperdino-0160"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "dapperdino-0160"